### ISSUE TITLE
how to not log in for every single edit?

### ISSUE THREAD

**Issue by rwst** [maxlath/wikibase-cli#120]
The way I use wikibase-cli (call `wd` with single edits) leads to unneccessary logins to Wikidata which is now discussed in https://phabricator.wikimedia.org/T256533. They cite https://www.mediawiki.org/wiki/API:Login#Additional_notes where we can read:
`If you are sending a request that should be made by a logged-in user, add assert=user parameter to the request you are sending in order to check whether the user is logged in. If the user is not logged-in, an assertuserfailed error code will be returned.`

Can your code do this between calls of `wd`? If not, can it be implemented? If not, would batch mode editing resolve it?

**Comment by maxlath** [comment]
yes, batch mode would resolve this.

Individual calls to `wd` do re-login every time, as cookies are not stored among session. We could consider implementing such a store. Alternatively, we could push people to use batch mode by displaying a warning when doing many successive edits without batch mode

**Comment by rwst** [comment]
> Individual calls to wd do re-login every time, as cookies are not stored between sessions.

Something like this would be helpful in the documentation.

**Comment by maxlath** [comment]
@rwst your pull requests to improve the documentation are welcome.

**Comment by maxlath** [comment]
I assume we can consider this addressed by #122 and close for now
