### ISSUE TITLE
Slightly confusing example in docs for label language

### ISSUE THREAD

**Issue by tmtmtmtm** [maxlath/wikibase-cli#123]
In `docs/read_operations.md`, it gives an example for `--lang`:

```
wd claims Q2001 P19 --lang ru
```

However running this currently gives me the output:

```
> wd claims Q2001 P19 --lang ru
Q18426
```

This confused me, as I was expecting "Бронкс". 

After playing around a bit more and reading more closely, what I think is happening here is that this option is about the language of the _property_ not the value (i.e. место рождения), but if there's only a single property being requested, the property label isn't displayed, so setting a language for it has no effect.

I'm not completely convinced enough about my understanding what's actually going on and what's meant to be going on to suggest a fix, but if the above is correct, then I think this should be an example that actually shows at least one label in Russian.

(Pointing from here to the place in the docs that explains how I can get Бронкс instead of, or as well as, Q18426 might also be helpful, as I still haven't been able to find that part)

**Comment by maxlath** [comment]
yep, I'm afraid that `wb claims` is doing different stuff, not always in an intuitive way :/

6152b2d removes that confusing example
