### ISSUE TITLE
Need to re-authenticate any time I upgrade

### ISSUE THREAD

**Issue by tmtmtmtm** [maxlath/wikibase-cli#124]
Every time I upgrade via `npm install -g wikibase-cli@latest`, the first edit I try to make triggers the reauth disalog:

```
This operation requires to set your crendentials for https://www.wikidata.org
Which authentication mechanism would you like to use to login to https://www.wikidata.org ?:
/!\ Beware that those will be stored in plain text on your computer
1 - OAuth tokens (recommended)
2 - username - password
```

(side note: there's also a typo there: "crendentials" instead of "credentials")

I always select 1, then provide all my details again, and everything is fine until the next time I upgrade, at which point it forgets who I am.

(on Mac, node at v14.4, via homebrew)

**Comment by maxlath** [comment]
my mistake was to try to keep those files in the module directory: I was not encountering the issue as I never have to upgrade from npm ><

from `v14.0.0`, all local files are saved in the [standard home directory](http://askubuntu.com/a/14536) (I don't know how standard that is for MacOS though), please see [changelogs](https://github.com/maxlath/wikibase-cli/blob/master/CHANGELOG.md#1400---2020-07-17) for how to not loose your credentials a last time while running this upgrade ;)

**Comment by tmtmtmtm** [comment]
this worked perfectly for me 🎉 

(I have no idea either how standard this directory is for macs, but I already have config there for other things)

Thank for a quick fix!

**Comment by tmtmtmtm** [comment]
Oh, no, I spoke too soon. This actually didn't work for me.

The documentation in the changelog asks me to write my old config to `~/.config/wikibase-cli/config.js` **but** the code actually looks for it in `config.json` not `config.js`

Moving the config I generated to that instead works. So fixing this should just be a matter of updating the documentation, rather than any code.

**Comment by maxlath** [comment]
done in 3ce9d6f, thanks for reporting!

**Comment by tmtmtmtm** [comment]
👍
