### ISSUE TITLE
deprecation batch stopped, because it wants "named as" qualifier to be a monolingual string

### ISSUE THREAD

**Issue by Jheald** [maxlath/wikibase-cli#128]
Hi Max,

I was trying to deprecate a batch of statements, but the batch stopped at
https://www.wikidata.org/wiki/Q5544505#Q5544505$CFBEFF20-60B3-4124-A206-F70A4FD45082  
with the command
{ "guid": "Q5544505$CFBEFF20-60B3-4124-A206-F70A4FD45082", "rank": "deprecated" }
giving the error 
invalid monolingualtext value { property: 'P1476',  value: 'George Sidney Shepherd, 1784–1858' }

This is odd on two counts: firstly the qualifier P1476 ("named as") takes string values, not monolingual text
Secondly, if the statement already exists, it ought to be possible to deprecate it

**Comment by maxlath** [comment]
it seems that P1476 does have a [`datatype=monolingualtext`](https://www.wikidata.org/w/api.php?action=wbgetentities&ids=P1476&format=json&props=info)

Which command where you using and which version?

**Comment by maxlath** [comment]
The internal serialization was loosing rich values (simplifying the mononlingual `{ text, language }` into `{ value }`, [preserving those rich values](https://github.com/maxlath/wikibase-edit/commit/12d27db8) seems to fix the problem.

Patch published in `v15.2.2`

**Comment by maxlath** [comment]
Closing this issue as this seems resolved, but feel welcome to reopen if that's not actually the case
