### ISSUE TITLE
Allow to add username to OAuth config

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikibase-cli#133]
A configuration file with both `username` and `oauth` leads to an error:

> Error: credentials can not be both oauth tokens, and a username and password

But a `username` is helpful to document which user OAuth credentials belong to. The error should only be thrown if all of the fields `username`, `password`, and `oauth` are given.

**Comment by maxlath** [comment]
the `username` and `password` fields are constrained, but you could use any other value, for example you could set `_username` to document the corresponding user

**Comment by nichtich** [comment]
Thanks, I'll use `description`!
