### ISSUE TITLE
Readme is using 404ed image

### ISSUE THREAD

**Issue by matkoniecz** [maxlath/wikibase-cli#135]
https://inventaire.io/public/images/inventaire-brittanystevens-13947832357-CC-BY-lighter-blue-4-banner-500px.png in https://raw.githubusercontent.com/maxlath/wikibase-cli/master/README.md ("You may also like" section) is 404ing.

**Comment by maxlath** [comment]
fixed (https://github.com/inventaire/inventaire-client/commit/c60a4bd), thanks!
