### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by matkoniecz** [maxlath/wikibase-cli#136]
"wikibase-edit: Edit Wikibase from NodeJS, used in wikibase-cli for all write operations" part of readme links to https://github.com/maxlath/wikibase-cli/blob/master/docs/write-operations that is 404

**Comment by matkoniecz** [comment]
Is it maybe supposed to link https://github.com/maxlath/wikibase-cli/blob/master/docs/write_operations.md ?

**Comment by maxlath** [comment]
fixed (ccf543a), thanks!
