### ISSUE TITLE
do not ask for asks for credentials in --dry mode

### ISSUE THREAD

**Issue by matkoniecz** [maxlath/wikibase-cli#138]
Thanks for well done installation docs!

-------

I followed https://github.com/maxlath/wikidata-scripting/tree/master/harvest_infobox and still got request to supply password & username.

Is it really necessary to give it in a read-only mode?

Maybe changes upstream in https://github.com/maxlath/wikibase-cli would be needed.

**Comment by maxlath** [comment]
that's now possible in wikibase-cli v15.8.5 :tada:
