### ISSUE TITLE
set baserevid?

### ISSUE THREAD

**Issue by rwst** [maxlath/wikibase-cli#139]
Hello,
is there a way to set `baserevid` in wikibase-cli (this is a API request parameter, see https://www.mediawiki.org/wiki/Wikibase/API#Request_Format).

Reason for asking is this phab: https://phabricator.wikimedia.org/T270003 which I'm sure you would find useful too.

**Comment by maxlath** [comment]
that's now possible in `v15.9.0`, see [`baserevid` documentation](https://github.com/maxlath/wikibase-cli/blob/master/docs/write_operations.md#baserevid)

**Comment by rwst** [comment]
Great! Thank you.
