### ISSUE TITLE
Default to Julian dates before 5 October 1582

### ISSUE THREAD

**Issue by Thunderforge** [maxlath/wikibase-cli#141]
When the Gregorian calendar was first introduced to replace the Julian calendar, Thursday 4 October 1582 was followed by Friday 15 October 1582. Therefore, we can safely assume that any date in this format before 5 October 1582 is in the Julian calendar and not the Gregorian calendar.

(Note that the final country to transition from the Julian calendar to the Gregorian calendar was Greece, with 15 Feb 1923 followed by 1 Mar 1923. Thus we can safely assume that any date 16 February 1923 or later is a Gregorian date. Any date in between could potentially be either calendar, depending on the country).

Since #78, it's possible to manually set the calendar to Julian, but I would like to see wikibase-cli default to the Julian calendar for all dates before 5 October 1582. This is the behavior of the web GUI of Wikidata, so we will be consistent.

**Comment by maxlath** [comment]
Should dates way in the past (ex: events somewhere between the big bang and 10000 years ago) also default to the Julian calendar?

**Comment by Thunderforge** [comment]
Good question about astronomical dates. I think we should match whatever the Wikidata web UI does. Speaking of which…

[This Wikidata help article](https://www.wikidata.org/wiki/Help:Dates#Entry_of_exact_dates), says the following:

> * On manual entry, the software defaults to [proleptic Gregorian calendar (Q1985727)](https://www.wikidata.org/wiki/Q1985727) from 1583.
> * Dates before are considered by default as proleptic [Julian calendar (Q1985786)](https://www.wikidata.org/wiki/Q1985786).
> * In the advanced options, the calendar model can be changed.

It doesn't have an exception for astronomical objects. I checked [Q2 Earth](https://www.wikidata.org/wiki/Q2)) and I see that it uses the Julian calendar for [P571 inception](https://www.wikidata.org/wiki/Property:P571). I also tried to add a new value to P571 and set it to `4540 million years BCE` (the same value as Earth); I observed that the web UI defaults the calendar to Julian.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/6200170/102275691-6c4aa500-3eeb-11eb-9abe-4027ac16877d.png">

Therefore, it seems like the Wikidata web UI has the simple rule of "any date before 5 October 1582 defaults to Julian", even for astronomical dates, and I think `wikibase-cli` can do the same. If anybody has access to the technical specs of this code in Wikidata's web UI, that would be helpful to examine as well.

**Comment by maxlath** [comment]
that should now be the default behavior in `v15.9.3`
