### ISSUE TITLE
Add symmetric property/edit multiple items

### ISSUE THREAD

**Issue by haansn08** [maxlath/wikibase-cli#144]
I have prepared a list of items I want to connect with [different from (P1889)](https://www.wikidata.org/wiki/Property:P1889):
```text
Q395330 Q28230734
Q85864592 Q20827132
Q15616625 Q97310450
...
```
I have this template in mind:
```js
module.exports = function(a, b) {
    return [
        {id: a, claims: {P1889: b}},
        {id: b, claims: {P1889: a}}
    ];
}
```
However `wd ee --batch template.js < list.txt` does not seem to like it.
How can I use `wikidata-cli` to quickly add statements which require editing multiple items?

**Comment by maxlath** [comment]
That should now be possible in `v15.10.0` (implemented in 4b66ee7): can you update and retry?

**Comment by maxlath** [comment]
I added a [generalized version of that template to the template collection](https://github.com/maxlath/wikibase-cli-template-collection/blob/master/edit/add_bidirectional_relation.js)

**Comment by haansn08** [comment]
Works perfectly. Thank you very much!
