### ISSUE TITLE
Define common options/option letters

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikibase-cli#15]
Before option letters become rare, better think about common options. The same letter should not be used for different options in different commands unless it's a very special command. So far there are:
- `-a, --labels` display/select/.. labels
- `-d, --debug`
- `-l, --lang` language a label to query, select, provide, display...
- `-o, -object` (to read and write claims)
- `-p, -property` (to read and write claims)
- `-p, --wikipedia` (why `-p`?)
- `r, --reset` clear a cache (could also be used for SPARQL and write operations)
- `-r, --raw` output raw SPARQL results (should better be `--format sparql`!)
- `-s, --subject` (to read and write claims)
- `-t, --limit` result number limit (plus alias `-1`...`-9`)

Some options could better be made arguments, for instance:

```
wd open wiki Q123 # open Wikipedia.if "wikipedia".startsWith(argv[1]) or argv[1] == "wp"
wd open dewiki Q123 # open German Wikipedia
```

I'd think about reserving for future use:
- `-c, --count` or `-c, --claim`?
- `-f, --format <format>' 
- `-q, --quiet' 
- `-i, --identifier` or `-i, --index`? 
- `-u, --uris` 
- `-n, --no-execute/--dry-run` to not perform any remote request
- `-m, --summary/--message <summary>` edit summary (like in git commit)
- `-v, --verbose' 
- `-w, --wiki/--site` for site such as dewiki

Anyway: better not assign option letters by first-come-first-serve but with a wider plan.

**Comment by maxlath** [comment]
the idea behind using **p** for `-p, --wikipedia` was that **w** would certainly create conflict if we come to include other Wikimedia projects such as Wikisource, Wikiquote, ... all starting by **w**. But that wasn't very inspired, as giving `-s, --wikisource`, and `-q, --wikiquote` isn't possible.
I like the idea of the `wd open dewiki` syntax!

**Comment by maxlath** [comment]
so an update on that: [options letters are re-used as much as possible](https://github.com/maxlath/wikibase-cli//blob/53e8767/lib/global_options_help.js), but there are some overlaps. I think it's ok to not go with a larger plan, while keeping this problematic in mind, and let open the possibility of breaking interfaces for a big re-organization of options in a major version (that would be properly documented in [changelogs](https://github.com/maxlath/wikibase-cli/blob/master/CHANGELOG.md))
