### ISSUE TITLE
Adding claim an qualifier at the same time?

### ISSUE THREAD

**Issue by EvaSeidlmayer** [maxlath/wikibase-cli#154]
I can add a claim to an item 
`wb edit-entitiy {'id': 'Q223813', 'claims': {'P242': {'value': 'Q223817', 'references': [{'P149': 'Q223807'}]}}}`
And afterwards it works to add a qualifier `
wb aq 'Q223813$8D9789BF-BA6E-4870-9687-F3079F1FBD69' P551 '21'`

Is there a way to add both at the same time? this does not work out: 
`wb edit-entity {'id': 'Q223813', 'claims': {'P242': {'value': 'Q223817', 'qualifier': [{'P95657': 'Gabriella Rustici'}, {'P551': '21'}], 'references': [{'P149': 'Q223807'}]}}}`

thank you!

**Comment by maxlath** [comment]
It's `qualifiers` and not `qualifier`, and `qualifiers` must be an object (unlike references that may be an array of objects):
```sh
wb edit-entity '{
  "id": "Q223813",
  "claims": {
    "P242": {
      "value": "Q223817",
      "qualifiers":
        {
          "P95657": "Gabriella Rustici"
          "P551": "21"
        }
      ],
      "references": [
        {
          "P149": "Q223807"
        }
      ]
    }
  }
}'
```

Notes:
* the JSON object must be quoted to not be interpreted as shell syntax
* I added newline breaks for readability, but it's fine without

**Comment by EvaSeidlmayer** [comment]
Fantastic! I only had to add a comma and remove a square bracket!

```
 '{
  "id": "Q223813",
  "claims": {
    "P242": {
      "value": "Q223817",
      "qualifiers":
        {
          "P95657": "Gabriella Rustici",
          "P551": "21"
        },
      "references": [
        {
          "P149": "Q223807"
        }
      ]
    }
  }
}'

```

Thank you very much!
