### ISSUE TITLE
wd open --wikipedia silently failing

### ISSUE THREAD

**Issue by tmtmtmtm** [maxlath/wikibase-cli#160]
- wikibase-cli version: 15.16.8
- OS version: macOS 11.6

Since upgrading to macOS 11.6, `wd open -p` has been silently failing in most cases.

Checking with -u shows that the URL being generated contains spaces, and is presumably therefore being rejected as invalid:

```sh
> wd o -p Q6279 -u                                
https://en.wikipedia.org/wiki/Joe Biden
```

(And, indeed, `wd o -p Q1744` works)

**Comment by maxlath** [comment]
in v15.16.9, you should now get the following:
```sh
wd o -p Q6279 -u
# https://en.wikipedia.org/wiki/Joe_Biden
```
Also, in anticipation of possible non-ascii/special characters encoding problems, those characters are now URL encoded:
```
wd o -p Q1541914 -l ar -u
# https://ar.wikipedia.org/wiki/%D8%AD%D9%83%D8%A7%D9%8A%D8%A9_%D8%A7%D9%84%D8%A3%D9%85%D8%A9_%28%D8%B1%D9%88%D8%A7%D9%8A%D8%A9%29
```

**Comment by tmtmtmtm** [comment]
That did the trick. Thanks for the quick fix!
