### ISSUE TITLE
set-sitelink does not work on redirecting articles

### ISSUE THREAD

**Issue by VojtechDostal** [maxlath/wikibase-cli#167]
Recently, it became possible to add redirecting sitelinks to Wikidata.
https://www.wikidata.org/wiki/Wikidata:Sitelinks_to_redirects

However, the wikibase-cli does not seem to expect that.
Instead, it redirects the page first and then tries to connect the new page and fails because that one is already connected elsewhere.

`processing line 1: Q56414469    cswiki  "Netín (část obce)"
error triggered by line: "Q56414469     cswiki  "Netín (část obce)"": failed-save: failed-save: The save has failed.
    at requestError (C:\Users\vojte\AppData\Roaming\npm\node_modules\wikibase-cli\node_modules\wikibase-edit\lib\request\parse_response_body.js:18:15)
    at module.exports (C:\Users\vojte\AppData\Roaming\npm\node_modules\wikibase-cli\node_modules\wikibase-edit\lib\request\parse_response_body.js:11:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runEditCommand (C:\Users\vojte\AppData\Roaming\npm\node_modules\wikibase-cli\lib\edit\edit_command.js:98:17)
    at async Stream.<anonymous> (C:\Users\vojte\AppData\Roaming\npm\node_modules\wikibase-cli\lib\edit\edit_command.js:159:9)
url: https://www.wikidata.org/w/api.php?action=wbsetsitelink&format=json&bot=true
response status: 200
response body: {"error":{"code":"failed-save","info":"The save has failed.","messages":[{"name":"wikibase-api-failed-save","parameters":[],"html":{"*":"Uložení se nezdařilo."}},{"name":"wikibase-validator-sitelink-conflict","parameters":["[https://cs.wikipedia.org/wiki/Net%C3%ADn cswiki:Netín]","[[Q72362|Q72362]]"],"html":{"*":"Odkaz <a class=\"external text\" href=\"https://cs.wikipedia.org/wiki/Net%C3%ADn\">cswiki:Netín</a> je již použit položkou <a href=\"/wiki/Q72362\" title=\"Q72362\">Q72362</a>. Možná mohou být položky <a href=\"/wiki/Help:Merge/cs\" title=\"Help:Merge/cs\">sloučeny</a> nebo jedna z nich <a href=\"/wiki/Wikidata:RfD\" class=\"mw-redirect\" title=\"Wikidata:RfD\">smazána</a>. Nebojte se <a href=\"/wiki/Wikidata:Mezi_bajty\" title=\"Wikidata:Mezi bajty\">zeptat</a>."}}],"*":"See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw1341"} {
  statusCode: 200,
  statusMessage: undefined,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      server: [Array],
      'x-content-type-options': [Array],
      'mediawiki-api-error': [Array],
      'x-frame-options': [Array],
      'content-disposition': [Array],
      'cache-control': [Array],
      vary: [Array],
      'content-type': [Array],
      'content-encoding': [Array],
      age: [Array],
      'x-cache': [Array],
      'x-cache-status': [Array],
      'server-timing': [Array],
      'strict-transport-security': [Array],
      'report-to': [Array],
      nel: [Array],
      'set-cookie': [Array],
      'accept-ch': [Array],
      'permissions-policy': [Array],
      'x-client-ip': [Array],
      'accept-ranges': [Array],
      'content-length': [Array]
    }
  },
  body: {
    error: {
      code: 'failed-save',
      info: 'The save has failed.',
      messages: [Array],
      '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.'
    },
    servedby: 'mw1341'
  },
  url: 'https://www.wikidata.org/w/api.php?action=wbsetsitelink&format=json&bot=true',
  context: {
    url: 'https://www.wikidata.org/w/api.php?action=wbsetsitelink&format=json&bot=true',
    body: { error: [Object], servedby: 'mw1341' }
  }
}`

**Comment by tmtmtmtm** [comment]
@VojtechDostal are you setting the "intentional sitelink to redirect" badge (Q70894304) in the same command? With that in place this is working for me. For example I just ran:

```sh
wd set-sitelink Q108610136 enwiki "Parliamentary Under-Secretary of State for Life Science" Q70894304
```

This updated successfully as https://www.wikidata.org/w/index.php?title=Q108610136&oldid=1768980942

Without that final Q70894304 I got an error similar to yours.

**Comment by VojtechDostal** [comment]
Oh, I did see the mention of "badges" in the instructions, but I had no idea intentional redirects are a badge. Sorry to raise this issue then! It works perfectly now.
