### ISSUE TITLE
wd search --type property does not find property

### ISSUE THREAD

**Issue by bablf** [maxlath/wikibase-cli#169]
The command `wd search --type property "drug used for treatment" --lang en` does not find any properties even though `drug or therapy used for treatment` exists. 

My question is how does the search work and how can it be improved? 

`drug used for treatment` seems to have been a used property a while ago. 
Here are some other old properties that can not be found any more: 
'drug used for treatment',
```
'number of representatives in an organization/legislature or won in elections',
'time of spacecraft orbit decay',
'name version for other gender',
'official color or colors'
```

**Comment by maxlath** [comment]
By default, the `wd search` command uses the [`wbsearchentities` API endpoint](https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities) (ex:  [searching `drug used for treatment`](https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&language=en&search=drug%20used%20for%20treatment&type=property)), which is not great for fuzzy search, as I far as I understand, its based on a simple MySQL search.

`wd search --cirrus` is a bit better, as it relies on ElasticSearch and the [`WikibaseCirrusSearch` extension](https://www.mediawiki.org/wiki/Help:Extension:WikibaseCirrusSearch/fr), but then the `--type` filder doesn't work.

Note that for that purpose, there is also the `wd props` command, which has it own filtering mechanism (ex: `wd props drug`), or can be piped to `grep`, or even better, to [`fzf`](https://github.com/junegunn/fzf), which does fuzzy search: `wd props | fzf --query 'drug used for treatment' --exit-0 --select-1`

**Comment by bablf** [comment]
Thanks for the swift response! fzf seems to work :hugs:

**Comment by bablf** [comment]
Some of the aliases returned by `wd search -j` also seem to contain the old name.

**Comment by maxlath** [comment]
@bablf `wd props` downloads the full list once, and then use that local list, which might be out-dated: you can use `wd props --reset` to force a refresh
