### ISSUE TITLE
stray argument in static js object example

### ISSUE THREAD

**Issue by gitonthescene** [maxlath/wikibase-cli#174]
- wikibase-cli version: documentation
- OS version: moot

I wasn't sure if this should count as a bug or not, but I think [this example](https://github.com/maxlath/wikibase-cli/blob/main/docs/write_operations.md#pass-data-as-a-static-js-object-file) in the doc is malformed.  There seems to be an extra argument under the `P369` claim.  I was confused as to what the value was supposed to be.

I was trying to use it to model my use case but got confused.  The `--generate-template` tool worked like a charm though and leads me to believe this example is malformed.

Regardsm

**Comment by maxlath** [comment]
I don't think it's malformed ([it works as expected when executed](https://www.wikidata.org/w/index.php?title=Q4115189&diff=prev&oldid=1815361062)): property claims arrays can accept either a single value or an array of values. Those values can either be simple values (ex: just an entity id such as `Q13406268`) or rich values (an object with `qualifiers` and/or `references`)

**Comment by gitonthescene** [comment]
So is the value for the property `P369` in this example `Q13406268` or `Q1992907`?

**Comment by maxlath** [comment]
Both, but the `Q1992907` claim also has qualifiers and references

**Comment by gitonthescene** [comment]
Oh, I see.  It’s two claims with the same property.  I hadn’t grokked that it was a list unlike the `P123` property above it.  Sorry for the noise.

**Comment by maxlath** [comment]
no worries :)
