### ISSUE TITLE
I can't install in paws

### ISSUE THREAD

**Issue by hubaishan** [maxlath/wikibase-cli#183]
I can't install in paws, is there a guide to install in paws?

**Comment by maxlath** [comment]
I'm not familiar with paws, is it that paws https://software.sil.org/paws/ ? Is there a known way to install npm packages in paws?

**Comment by hubaishan** [comment]
@maxlath  No, It is https://wikitech.wikimedia.org/wiki/PAWS

**Comment by hubaishan** [comment]
I made this feature request 
https://phabricator.wikimedia.org/T358649

Correction It installed successfully but without direct links.

The installation process is:

1. open terminal windows.
2. `npm install wikibase-cli@16.3.3`
3. we can run by `node node_modules/wikibase-cli/bin/wd` not `wd` directly
4. configure your OAuth keys
5. if server stopped you must reinstall and reconfigure.

**Comment by hubaishan** [comment]
@maxlath 
please review the pull request https://github.com/toolforge/paws/pull/381

**Comment by hubaishan** [comment]
It is now part of default paws installation after https://github.com/toolforge/paws/pull/381.

**Comment by maxlath** [comment]
@hubaishan nice! sorry I missed the previous notification
