### ISSUE TITLE
provide Oauth support instead of username/password

### ISSUE THREAD

**Issue by jmdugan** [maxlath/wikibase-cli#25]
did some research on what this would take, here are the background reading I found.

oauth overview
https://www.mediawiki.org/wiki/Help:OAuth

very simple "Hello world" program to show how to use OAuth
https://tools.wmflabs.org/oauth-hello-world/

background
https://www.mediawiki.org/wiki/OAuth/For_Developers

propose app for oauth
https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose

command line comparable
https://stackoverflow.com/questions/5877326/command-line-tools-for-accessing-apis-with-oauth-support

command line oauth example with python
http://www.benmccann.com/oauth-in-a-command-line-script/

node suggestions for mediawiki
https://www.mediawiki.org/wiki/OAuth/For_Developers#Node.js
https://www.npmjs.com/package/passport-mediawiki-oauth

**Comment by maxlath** [comment]
OAuth is now integrated to [wikidata-edit](https://github.com/maxlath/wikidata-edit) since [28ef3ba](https://github.com/maxlath/wikidata-edit/commit/28ef3ba) so that's totally possible, the problem is more in the setup workflow. I note here the idea you suggested orally to output a URL the user would have to open in a browser before returning a token to save instead of entering a password.

**Comment by revi** [comment]
Maybe let users make an [owner-only consumer](https://www.mediawiki.org/wiki/OAuth/Owner-only_consumers)? They will get credentials to put upon registration and that will be enough. (Meanwhile, we have [BotPasswords](https://www.mediawiki.org/wiki/Manual:Bot_passwords).)

**Comment by nichtich** [comment]
Maybe [this setup workflow helps](https://developer.okta.com/blog/2018/07/16/oauth-2-command-line) to simplify the "login" process (getting a fresh token if required): the user would get directed to a browser window but the script would get a token without need of manual copy & paste.

**Comment by maxlath** [comment]
OAuth authentification is now possible (and recommanded!) in `wikibase-cli >= v8` \o/
see [config documentation](https://github.com/maxlath/wikibase-cli/blob/master/docs/config.md)
