### ISSUE TITLE
option for yaml output instead of json

### ISSUE THREAD

**Issue by fuddl** [maxlath/wikibase-cli#35]
[YAML](http://yaml.org/) is a _is a human friendly data serialization standard_. As there is a [javascript library](https://github.com/nodeca/js-yaml) for that, it should be easy to implement.

**Comment by maxlath** [comment]
the lib you linked to seems to be to parse YAML, not to generate YAML from JSON or a js object, do you think that [this one](https://github.com/rafeca/prettyjson) would be a acceptable replacement? You need the YAML output just for the readability right?

**Comment by loominade** [comment]
> the lib you linked to seems to be to parse YAML, not to generate YAML from JSON

no, it also [serialises into YAML](https://github.com/nodeca/js-yaml#safedump-object---options-)

**Comment by maxlath** [comment]
how about relying on an external converter like [`json2yaml`](https://www.npmjs.com/package/json2yaml)?
```sh
npm install -g json2yaml
wd data Q123 | json2yaml
```
