### ISSUE TITLE
Add command wd-filter

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikibase-cli#66]
Include functionality of wikidata-filter and add some options also supported by `wd-data`, such as `--keep` and `--props`.

**Comment by maxlath** [comment]
`wikidata-filter`, now called `wikibase-dump-filter`, is quite a beast of its own with a rather specific environment - namely working with JSON dumps -, it makes more sense to me to keep it separated.

and it already has a [`--keep`](https://github.com/maxlath/wikibase-dump-filter/blob/master/docs/cli.md#filter-attributes) option
