### ISSUE TITLE
Dump existing item as JSON

### ISSUE THREAD

**Issue by antifa-ev** [maxlath/wikibase-cli#68]
How can I dump an existing item as JSON?

I would like to create new items from csv column data while using JSON 'skeleton' files. Have you once tried something?
`
wd edit-item ./new_item_data.json`

**Comment by maxlath** [comment]
I just published `v7.3.0`, which includes a new command based on this idea of preparing a skeleton or *template* from an existing item: [`wd generate-template`](https://github.com/maxlath/wikidata-cli/blob/master/docs/read_operations.md#wd-generate-template). Could you give it a try to tell me if that meets your expectations?
