### ISSUE TITLE
Select Julian dates

### ISSUE THREAD

**Issue by generalist** [maxlath/wikibase-cli#78]
A small feature request: is it possible for the date edits to allow the user to specify a calendar? 

At the moment, all date edits are put through as Gregorian, eg/ `wd ac Q4115189 P580 '1402-02-26'` -> [result](https://www.wikidata.org/w/index.php?title=Q4115189&type=revision&diff=962538997&oldid=962536635)

It would be great if we could have some way to explicitly set a date to be Julian if desired. (Defaulting to Gregorian unless specifically stated otherwise would probably be sensible - most people won't need to think about calendar schemes)

Thanks!

**Comment by maxlath** [comment]
it's now ([v15.2.0](https://github.com/maxlath/wikibase-cli/blob/master/CHANGELOG.md#1520---2020-08-07) possible:
```sh
wd ac Q4115189 P580 '{"time":"1402-02-26","calendar":"julian"}'
```
I'm not sure I get the subtleties of Julian dates, so please let me know if you see anything weird
