### ISSUE TITLE
Extend JS file templates with metadata

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikibase-cli#81]
As [described here](https://github.com/maxlath/wikibase-cli/blob/master/docs/write_operations.md#wd-edit-item) a JS file can be used as template. Option `--dry` emits the JSON data generated from the template, e.g.:

    $ wd ei ./template.js Q1 abc 123 --dry

But how do I document the template to remember which parameters to pass to the template? How about supporting 

    $ wd ei ./template.js --help
    Usage: wd ei ./template.js <id> <name> [quantity]
    Adds some special statements.
   
By extension of the exported function with fields `args` and `description`:

~~~js
module.exports = (id, name, quantity) => {
  return {
    id,
    claims: {
      P1449: name,
      ...(quantity ? { P1106: parseInt(quantity)} : {}) // optional
  }
}
module.exports.args = ['id', 'name', 'quantity?']
module.exports.description = "Adds some special statements."
~~~

Additional use of `args` (although I'm not sure whether array, object or string): wd can detect missing arguments and raise an error instead of passing bogus data to Wikibase backend.

The arguments might also depend on whether `edit-item` or `create-item` was used:

~~~js
module.exports.args = {
  edit: ['id', 'name', 'quantity?'],
  create: ['id?', 'name', 'quantity?']
}
~~~

However the optionality of argument `id` as first argument may be a hard-coded best-practice instead.

**Comment by maxlath** [comment]
I gave it a shot here https://github.com/maxlath/wikibase-cli/pull/119
could you try to see if that works as you expected?

**Comment by maxlath** [comment]
> However the optionality of argument `id` as first argument may be a hard-coded best-practice instead.
I just worked on [a case where the initial input is a Wikipedia article url instead](https://github.com/maxlath/wikidata-scripting/blob/ff92e56/harvest_infobox/template.js), and that looked rather like a nice possibility

**Comment by maxlath** [comment]
A first implementation of that template-specific help menu has been added in `v15.4.0`: [template help menu](https://github.com/maxlath/wikibase-cli/blob/master/docs/write_operations.md#template-help-menu)

I'm thus closing this issue for now, but feel welcome to reopen it or open new ones for modifications of that feature
