### ISSUE TITLE
make clear in readme if the the tool can work on Windows 

### ISSUE THREAD

**Issue by vojtechhuser** [maxlath/wikibase-cli#82]

**Comment by maxlath** [comment]
I don't have a Windows machine at hand, could you try to `npm install wikibase-cli@latest` and tell me how it goes?

**Comment by VladimirAlexiev** [comment]
@vojtechhuser I use Win10 and just upgraded to the latest version and didn't have the issue $72. (I've reported some seg faults previously).
@maxlath Will keep you posted if I hit any errors.

**Comment by VojtechDostal** [comment]
I've just been trying to install this on Windows but I've ran into similar issues as those reported in #72 

Install with npm seemed to go smoothly - as far as I can tell, I'm not an expert - but running the "wd summary Q5" command from my command line returns an error - "Sh is not a recognizable command...", which seems to be similar to what others have reported.

**Comment by maxlath** [comment]
@VojtechDostal do you get the same error with `wb summary Q5 --instance https://www.wikidata.org`?

**Comment by VojtechDostal** [comment]
> @VojtechDostal do you get the same error with `wb summary Q5 --instance https://www.wikidata.org`?

That does work! What have  missed or forgotten to configure? :)

**Comment by maxlath** [comment]
`wd` is just a convenience executable that calls `wb`, but [in its current implementation, it explicitly requires to do that in a `sh` environment](https://github.com/maxlath/wikibase-cli/blob/29eaeab/bin/wd). Maybe removing that first line would let the choice of the shell type to the executing context: could you try to remove that line in your local installation and see if `wd summary Q5` works?

**Comment by VojtechDostal** [comment]
After removing the 1st line from "wd" file, I restarted the command line window and tried "wd summary Q5" again but the problem remains the same

![image](https://user-images.githubusercontent.com/21329813/151534398-e9f7190e-e6d8-4e04-93a1-75050cbf17e4.png)

**Comment by maxlath** [comment]
I rewrote `wd` as a `node` script in 2a4eaa0, published in `v15.16.1`: can you upgrade and retry `wd summary Q5`?

**Comment by VojtechDostal** [comment]
> I rewrote `wd` as a `node` script in [2a4eaa0](https://github.com/maxlath/wikibase-cli/commit/2a4eaa0edc578ad603123ce02455a9b1ddbaf58b), published in `v15.16.1`: can you upgrade and retry `wd summary Q5`?

 I upgraded and tried again, attaching results:

![image](https://user-images.githubusercontent.com/21329813/151542894-c3061fb5-cef6-469c-8898-d260cb07fdae.png)

So there seems to be a different error this time.

**Comment by maxlath** [comment]
new attempt :D 38a9ea8 published in `v15.16.3`

**Comment by VojtechDostal** [comment]
Sorry for taking a bit longer :)

This seemed to have worked. After update, I tried the following command:

wd update-claim Q4466817$72dfdfa0-4c71-7806-6d8c-dc7b316148a6 "Thuja occidentalis ʽSmaragd’"
--> https://www.wikidata.org/w/index.php?title=Q4466817&diff=prev&oldid=1573856361

Thanks! 👍

**Comment by maxlath** [comment]
Regarding the original issue, I added a mention that Windows should be part of the supported system: a1b780a
