### ISSUE TITLE
wd --help should show main command description

### ISSUE THREAD

**Issue by waldyrious** [maxlath/wikibase-cli#87]
I expected to see a description of the main `wd` command when calling it with the `--help` option:

```
❯ wd --help

  Usage: wd [options] [command]

  Options:

    -V, --version                   output the version number
    -h, --help                      output usage information

  Commands:

    ...
```

IMO there should be a `Description` field alongside `Usage`, `Options` and `Commands` (or simply the string above the `Usage` line), but there was none.

I tried to figure out how to do this myself; the [commander documentation](https://www.npmjs.com/package/commander) suggests using `.description()`, but [`bin/wd`](https://github.com/maxlath/wikibase-cli/blob/75033267b/bin/wd) seems too smart now; [apparently](https://github.com/maxlath/wikibase-cli/blob/75033267b/lib/program.js#L10-L11) the description is extracted from the metadata which should be [here](https://github.com/maxlath/wikibase-cli/tree/75033267b/metadata) somewhere, but there's no entry for the main commands there; and to add on top of my confusion, [`lib/program.js`](https://github.com/maxlath/wikibase-cli/blob/75033267b/lib/program.js#L23) seems to suggest that the help flag only shows command examples? I'm confused! 😅

**Comment by waldyrious** [comment]
Maybe there needs to be some Implementation notes / Contributing documentation explaining the overall architecture of the project, to allow other people to contribute more easily :)

**Comment by maxlath** [comment]
A description was added in de17e57, so I close this issue, but you're welcome to suggest a better description
