### ISSUE TITLE
wd ee troubles

### ISSUE THREAD

**Issue by VladimirAlexiev** [maxlath/wikibase-cli#93]
After adding OAuth tokens:

```
$ wd data Q95 | wd ee
/cygdrive/c/Users/vladimir.alexiev.000/AppData/Roaming/npm/wb: line 14: 11504 Segmentation fault      node "$basedir/node_modules/wikibase-cli/bin/wb" "$@"

  Usage: wd-edit-entity [options] <data>

  Edit an existing entity

  Options:

    -v, --verbose                make the output more verbose
    -d, --dry                    output the generated data, do not run the query
    -h, --help                   output usage information
```

If I use an intermediate file:

```
$ wd data Q95 > data.json
$ wd ee data.json
invalid property id { propertyId: 'hash' }
```

**Comment by maxlath** [comment]
`wd ee` currently doesn't check its stdin, so piped data will be ignored

**Comment by maxlath** [comment]
as for the intermediary file, `wd ee` actually expects a simplified format, so it is recommended to use [`wd generate-template` (`wd gt`)](https://github.com/maxlath/wikidata-cli/blob/master/docs/read_operations.md#wb-generate-template)

**Comment by maxlath** [comment]
Closing as this issue is inactive. Please reopen if you still have troubles with the latest version.
