### ISSUE TITLE
Suppress error messages

### ISSUE THREAD

**Issue by tarnh** [maxlath/wikibase-cli#97]
Dear Max,

I'm using `wd id $article_string` since severals years in my scripts. Thank you very much for your tool!

As far as I remember just a few version ago there were no error messages like `Error: id not found`.

How may I suppress any error message from `wikibase-cli` for usage with bash one-liner scripts?

**Comment by maxlath** [comment]
you could ignore errors "the shell way" by redirecting [`stderr`](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)) :
```sh
wd id "$article_string" 2> /dev/null
```
would that be enough for your need?
